### ISSUE TITLE
Quelques bugs après l'installation

### ISSUE THREAD

**Issue by yoyossef** [morhue/FF7SYWLinuxInstaller#16]
Merci beaucoup pour ce script très utile de prime abord, j'ai pu faire la majorité de ma run sur Steam Deck tranquillement via ça.

J'ai essayé de l'installer sur mon installation Arch Linux PC de bureau, mais j'ai rencontré quelques problèmes que j'ai su régler à la main mais préfère en faire un rapport : 

- Dans le `pfx` le jeu était installé dans `Jeux/FF7SYW` au lieu de `Games/FF7SYW` par conséquent les scripts pointaient vers le mauvais dossier, donc c'est sûrement dû au fait que mon installation Linux soit en locale FR, le script d'installation était terminé et j'ai eu comme message `FF7SYW n'est pas installé`. Pour réparer ça j'ai supprimé le dossier `Games` vide et j'ai renommé le dossier `Jeux` par `Games`

- Pour lancer FF7SYW les chemins des `.exe` étaient erronés, Proton lançait `$HOME/.local/share/Steam/steamapps/compatdata/FF7SYW/pfx/drive_c/Games/FF7SYWV5/FF7SYWV5/FF7_SYW_Configuration.exe &` au lieu de `$HOME/.local/share/Steam/steamapps/compatdata/FF7SYW/pfx/drive_c/Games/FF7SYWV5/FF7_SYW_Configuration.exe &`

Après ces deux modifications ça a l'air de bien se passer.

**Comment by morhue** [comment]
Bonjour, merci beaucoup pour ton retour !
 je n'ai pas fait de test sur une pure Arch récemment.
Tu as bien utilisé l'archive de release et pas le code master?
Pourrais-tu m'envoyer ton log d'installation, stp?
Pour le problème 1, je force des locales us sur Proton, malheureusement, ça n'as pas l'air de faire le job avec une arch en Français.
Pour le 2nd, je laisse le path par défaut de l'installer qui pointe sur c:/Games/FF7SYWV5 et l'installer créer un nouveau répertoire FF7SYWV5.
Normalement, il ne devrait plus y avoir ce genre de soucis quand j'activerai l'installation silencieuse des packages pour la prochaine maj.
Hésites pas à venir demander du support sur le discord.

**Comment by yoyossef** [comment]
J'ai suivi le tuto du readme donc j'ai clone le repo et utilisé la version master, je n'avais pas vu qu'il y avait des releases maintenant

**Comment by morhue** [comment]
Ok, merci pour l'information. Je mettrai a jour le README en ce sens. De tte façon, si tu as utilisé la master venant du PR de ce matin, c'est propre et bug free sur SteamDeck.

Pour info, je vais rajouter une création d'un répertoire Games dans le compatdata pour les systèmes en locales non US. J'avais pas pensé a ce cas.

**Comment by morhue** [comment]
Pour résumé:
-Update README to prevent user to use last release and not master
-Create a directory Games in c:\
-Activate silent install added on latest packages by Satsuki to force to use right directories.

**Comment by morhue** [comment]
-Update README to prevent user to use last release and not master -> OK
-Create a directory Games in c: -> OK
-Activate silent install added on latest packages by Satsuki to force to use right directories. -> https://github.com/morhue/FF7SYWLinuxInstaller/issues/17 -> will be done in v0.3
